# Generated by Django 5.2.1 on 2025-05-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0002_alter_product_options_alter_product_active_and_more'),
        ('eshop_products_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='eshop_products_category.productcategory', verbose_name='دسته بندی'),
        ),
    ]
