# Generated by Django 5.2.1 on 2025-05-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop_products", "0005_alter_productgallery_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured",
            field=models.BooleanField(default=False, verbose_name="محصول ویژه"),
        ),
    ]
