# Generated by Django 5.2.1 on 2025-05-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eshop_products", "0006_product_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="visits",
            field=models.IntegerField(default=0, verbose_name="تعداد مشاهده"),
        ),
    ]
