# Generated by Django 5.2.4 on 2025-07-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0007_product_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='course_duration',
            field=models.CharField(blank=True, help_text='12:30', max_length=6, null=True, verbose_name='(ساعت:دقیقه)مدت زمان دوره'),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام ناشر'),
        ),
    ]
