# Generated by Django 5.2.4 on 2025-07-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0008_product_course_duration_product_publisher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='course_duration',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='مدت زمان دوره'),
        ),
    ]
