# Generated by Django 5.2.1 on 2025-05-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0002_contactus_read_contactus_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده/نشده'),
        ),
    ]
