# Generated by Django 5.2.1 on 2025-05-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sliders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدر ها'},
        ),
    ]
